[master]
10.6.249.109 ansible_user=ubuntu ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[workers]
10.6.249.8 ansible_user=ubuntu ansible_ssh_common_args='-o StrictHostKeyChecking=no'
10.6.249.59 ansible_user=ubuntu ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[k3s_cluster:children]
master
workers
