[master]
3.70.171.92 ansible_user=ubuntu ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ServerAliveInterval=60' private_ip=10.0.0.79

[workers]
3.120.147.134 ansible_user=ubuntu ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ServerAliveInterval=60'
63.182.253.137 ansible_user=ubuntu ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ServerAliveInterval=60'

[k3s_cluster:children]
master
workers
