[master]
3.79.246.74 ansible_user=ubuntu ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ServerAliveInterval=60' private_ip=10.0.0.79

[workers]
3.72.14.177 ansible_user=ubuntu ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ServerAliveInterval=60'
18.192.66.143 ansible_user=ubuntu ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ServerAliveInterval=60'

[k3s_cluster:children]
master
workers
